name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0595645590c54f245fb1bc106cb992355a9a79c0d705c793d5deea118034ace"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
