name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0dc405b60fd13ca83cf1efdd12bd1f6afbacdf3e913c725a930d8a1ba114a1cf"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
