name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b413d01a8e463c1e02cde76bc5cecdbe217679799cf7c33ab2b33779f09c68af"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
