name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "180afe9bbf36042c4c7ff8865ca217000b72edd72489acaf343faebc3680ac22"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
