name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59d24ef54cb44c931645ddc41dd614f5531e20aaaf9df3622b66a4bad4fcfa49"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
