name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "565ad2f8b070c0f939c6ba9d53549669ce4ea5d6e2243fb75767abe754f53b3f"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
