name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65fd339df3072bc1e0929cdb4ea3e7e65eec062d4f2277fc77e6ed1cb6f36333"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
