name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.13.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9648ff4f5432c997c1ca9c0cd03a7d55394d580bedaf6e1822f469728747ba2e"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
