name = "GregTech CEu Modern Community Pack - Project 18"
author = "ursamina"
version = "1.14.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7e85414fef93b8b859709a3a367f43c62b0c87d6e9cf77541db05bdd0aeff37"

[versions]
forge = "47.4.6"
minecraft = "1.20.1"
