name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb709ce9f78a59c6dfa88862204d05b6ca625b3cea7bded966031d0567e39f16"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
