name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.11.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0d1479489a1f8e87f8f766e9bae3a6bfec461c72eb241398af7275705aee828"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
