name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43f65a2798bd40212eb2f35a4fb8f6d3d25576d96b4edf2780b9bcfb01e7c5cd"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
